# Generated by Django 5.2.17 on 2026-09-13 02:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('formal', 'Formal Education'), ('program', 'Educational Program'), ('certification', 'Certification'), ('course', 'Course / Training')], default='formal', max_length=30)),
                ('thumbnail', models.URLField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
